import {
  Activity,
  AlertCircle,
  Anchor,
  Archive,
  AtSign,
  BadgeCheck,
  Ban,
  Bot,
  Braces,
  Brain,
  BrainCircuit,
  Building2,
  CalendarDays,
  ChartNoAxesColumn,
  Check,
  CircleHelp,
  Clapperboard,
  ClipboardCheck,
  Clock,
  Clock3,
  Clock4,
  CloudLightning,
  Compass,
  Cookie,
  Copy,
  Crosshair,
  Database,
  DatabaseZap,
  DollarSign,
  Download,
  Eraser,
  EyeOff,
  File,
  FileJson,
  Files,
  FileSearch,
  FileText,
  FileWarning,
  Filter,
  Folder,
  FolderKanban,
  FolderTree,
  FormInput,
  Gauge,
  GitBranch,
  Globe,
  Globe2,
  GraduationCap,
  Grid,
  HardDrive,
  Hash,
  Heading,
  HeartPulse,
  Image,
  Images,
  Info,
  Key,
  Keyboard,
  Layers,
  Link,
  List,
  ListChecks,
  ListFilter,
  ListOrdered,
  ListRestart,
  ListStart,
  ListTree,
  Lock,
  Map as MapIcon,
  Maximize,
  MessageCircle,
  MessageCircleMore,
  MessageCircleQuestion,
  MessageCircleWarning,
  MessageSquare,
  MessageSquareMore,
  MessagesSquare,
  Mic,
  Minimize2,
  Monitor,
  Network,
  Package,
  Palette,
  PanelTop,
  PauseCircle,
  Percent,
  Power,
  Quote,
  RefreshCcw,
  RefreshCw,
  Regex,
  Repeat,
  Route,
  Rows3,
  Ruler,
  Save,
  Scissors,
  ScrollText,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Sliders,
  SlidersHorizontal,
  Smile,
  Sparkles,
  StickyNote,
  Tag,
  Tags,
  Target,
  Terminal,
  Text,
  TextCursorInput,
  Thermometer,
  Timer,
  TimerReset,
  Trash2,
  Type,
  User,
  UserCircle,
  UserRoundCheck,
  UserRoundPen,
  UserRoundSearch,
  Users,
  UsersRound,
  Variable,
  Volume2,
  VolumeX,
  WandSparkles,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * 后端配置 schema 使用 kebab-case 图标名。这里显式列出受支持的图标，
 * 避免通过命名空间反射把整套 lucide-react 图标打进首屏包。
 */
const SCHEMA_ICONS = {
  activity: Activity,
  'alert-circle': AlertCircle,
  anchor: Anchor,
  archive: Archive,
  'at-sign': AtSign,
  'badge-check': BadgeCheck,
  ban: Ban,
  bot: Bot,
  braces: Braces,
  brain: Brain,
  'brain-circuit': BrainCircuit,
  'building-2': Building2,
  'calendar-days': CalendarDays,
  'chart-no-axes-column': ChartNoAxesColumn,
  check: Check,
  'circle-help': CircleHelp,
  clapperboard: Clapperboard,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  'clock-3': Clock3,
  'clock-4': Clock4,
  'cloud-lightning': CloudLightning,
  compass: Compass,
  cookie: Cookie,
  copy: Copy,
  crosshair: Crosshair,
  database: Database,
  'database-zap': DatabaseZap,
  'dollar-sign': DollarSign,
  download: Download,
  eraser: Eraser,
  'eye-off': EyeOff,
  file: File,
  'file-json': FileJson,
  'file-search': FileSearch,
  'file-text': FileText,
  'file-warning': FileWarning,
  files: Files,
  filter: Filter,
  folder: Folder,
  'folder-kanban': FolderKanban,
  'folder-tree': FolderTree,
  'form-input': FormInput,
  gauge: Gauge,
  'git-branch': GitBranch,
  globe: Globe,
  'globe-2': Globe2,
  'graduation-cap': GraduationCap,
  grid: Grid,
  'hard-drive': HardDrive,
  hash: Hash,
  header: Heading,
  'heart-pulse': HeartPulse,
  image: Image,
  images: Images,
  info: Info,
  key: Key,
  keyboard: Keyboard,
  layers: Layers,
  link: Link,
  list: List,
  'list-checks': ListChecks,
  'list-filter': ListFilter,
  'list-ordered': ListOrdered,
  'list-restart': ListRestart,
  'list-start': ListStart,
  'list-tree': ListTree,
  lock: Lock,
  map: MapIcon,
  maximize: Maximize,
  'message-circle': MessageCircle,
  'message-circle-more': MessageCircleMore,
  'message-circle-question': MessageCircleQuestion,
  'message-circle-warning': MessageCircleWarning,
  'message-square': MessageSquare,
  'message-square-more': MessageSquareMore,
  'messages-square': MessagesSquare,
  mic: Mic,
  'minimize-2': Minimize2,
  monitor: Monitor,
  network: Network,
  package: Package,
  palette: Palette,
  'panel-top': PanelTop,
  'pause-circle': PauseCircle,
  percent: Percent,
  power: Power,
  quote: Quote,
  'refresh-ccw': RefreshCcw,
  'refresh-cw': RefreshCw,
  regex: Regex,
  repeat: Repeat,
  route: Route,
  'rows-3': Rows3,
  ruler: Ruler,
  save: Save,
  scissors: Scissors,
  'scroll-text': ScrollText,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  shuffle: Shuffle,
  sliders: Sliders,
  'sliders-horizontal': SlidersHorizontal,
  smile: Smile,
  sparkles: Sparkles,
  'sticky-note': StickyNote,
  tag: Tag,
  tags: Tags,
  target: Target,
  terminal: Terminal,
  text: Text,
  'text-cursor-input': TextCursorInput,
  thermometer: Thermometer,
  timer: Timer,
  'timer-reset': TimerReset,
  'trash-2': Trash2,
  type: Type,
  user: User,
  'user-circle': UserCircle,
  'user-round-check': UserRoundCheck,
  'user-round-pen': UserRoundPen,
  'user-round-search': UserRoundSearch,
  users: Users,
  'users-round': UsersRound,
  variable: Variable,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'wand-sparkles': WandSparkles,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>

function normalizeIconName(iconName: string): string {
  return iconName
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Za-z])(\d)/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase()
}

export function resolveSchemaIcon(iconName: string | undefined): LucideIcon | undefined {
  if (!iconName) {
    return undefined
  }

  const normalizedIconName = normalizeIconName(iconName)
  return SCHEMA_ICONS[normalizedIconName as keyof typeof SCHEMA_ICONS] ?? CircleHelp
}
